### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [ConcaveTrillion/hilaire-belloc_the-four-men#2]
### General:

- [x] The graphite grades are not abbreviations but alphanumeric codes. Remove the `<abbr>`s and periods. Make these changes an [Editorial] commit.

### dedication.xhtml:

- [x] The text doesn't need to be in a `<blockquote>`. It isn't a quotation.

### chapter-3.xhtml:

- [x] The numbered song stanzas should all be inside a single `<blockquote>`. You can separate each stanza with `<div>`s.

- [x] The bracketed text in the songs are also stage directions. The blockquotes should be structured like:
```
			<blockquote>
				<p>[<i>Semi-chorus</i>.]</p>
				<div epub:type="z3998:song">
				<p>
					<span>“Oh, he didn’t believe</span>
					<br/>
					<span>In Adam and Eve,</span>
					<br/>
					<span class="i1">He put no faith therein!</span>
					<br/>
					<span>His doubts began</span>
					<br/>
					<span>With the fall of man,</span>
					<br/>
					<span class="i1">And he laughed at original sin!”</span>
				</p>
				</div>
			</blockquote>
```

- [x] The list should be in a `<blockquote>`.

- [x] The emphasized stanza should be formatted like:
```
				<p>
					<span>
						<em>“Oh, I thank my God for this at the least,</em>
					</span>
					<br/>
					<span>
						<em>I was born in the West and not in the East,</em>
					</span>
					<br/>
					<span>
						<em>And He made me a human instead of a beast,</em>
					</span>
					<br/>
					<span class="i1">
						<em>Whose hide is covered with hair!”</em>
					</span>
				</p>
```

### chapter-4.xhtml:

- [x] The table should be converted into an unordered list.

### local.css

- [x] The styling for `class="i4"` should be:
```
p span.i4{
	padding-left: 5em;
	text-indent: -1em;
}
```

- [x] The custom dedication CSS:
```
section#dedication blockquote{
	font-variant: small-caps;
}
```
needs to be replaced with:
```
[epub|type~="dedication"] p{
	font-variant: small-caps;
}
```

- [x] You can use the following CSS for unordered lists:
```
/* Unordered list */
ul{
	list-style-type: none;
	margin: 0;
	padding: 0;
}

section#chapter-4 ul li{
	padding-left: 5.5em;
}

section#chapter-4 ul li:last-child{
	padding-left: 0;
}
/* End unordered list */
```

- [x] Remove:
```
section#chapter-3 blockquote:nth-of-type(14) p:nth-of-type(3){
	font-style: italic;
}
```

content.opf:

- [x] You can replace:
```
		<dc:contributor id="transcriber-1">Anonymous</dc:contributor>
		<meta property="file-as" refines="#transcriber-1">Anonymous</meta>
		<meta property="role" refines="#transcriber-1" scheme="marc:relators">trc</meta>
```
by adding the role `<meta property="se:role" refines="#producer-1" scheme="marc:relators">trc</meta>` under the producer metadata.

**Comment by ConcaveTrillion** [comment]
Corrected all of these, thanks for the help.

One item - in the stage directions for Semi-Chorus and Chorus, in some of the songs it was indenting them when they followed an existing stanza. I added CSS to eliminate the hanging indent for these. I wasn't sure if using the 'continued' class would be appropriate there or not.

Also I checked several more scans for the first big song, later editions corrected the indentation, so I fixed that and that gets rid of the i4 selector all together.

**Comment by ConcaveTrillion** [comment]
Now that I think about it, maybe I did those wrong, and should have left each semi-chorus and chorus as its own blockquote. Let me know if that's what it should be. Sorry for the confusion

**Comment by EmmaSweeney** [comment]
Use `class="continued"` for the stage directions. Everything else looks good.

**Comment by ConcaveTrillion** [comment]
CSS fixed and added class. Also, I missed an incorrect <i> tag (when I had created the personas I had used a find/replace).

Should be good to go!
